# Generated by Django 3.2.7 on 2021-11-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name="Your child's name")),
                ('upload', models.ImageField(upload_to='uploads', verbose_name='')),
            ],
        ),
    ]
