# Generated by Django 3.2.7 on 2021-11-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0003_alter_uploadmodel_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadConfirmationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_name', models.CharField(max_length=100)),
                ('upload', models.ImageField(upload_to='uploads', verbose_name='Upload Confirmation')),
            ],
        ),
        migrations.RenameField(
            model_name='uploadmodel',
            old_name='user',
            new_name='username',
        ),
    ]
