# Generated by Django 3.2.7 on 2021-11-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0004_auto_20211116_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadModel',
        ),
        migrations.RenameField(
            model_name='uploadconfirmationmodel',
            old_name='users_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='uploadconfirmationmodel',
            name='amount_paid',
            field=models.CharField(default=0, max_length=50, verbose_name='Input Amount Here'),
            preserve_default=False,
        ),
    ]
