# Generated by Django 3.2.7 on 2021-11-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0006_uploadconfirmationmodel_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadconfirmationmodel',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='uploadconfirmationmodel',
            name='payment_mode',
            field=models.CharField(choices=[('ussd', 'USSD'), ('deposit', 'Deposit'), ('POS', 'POS_Transfer')], default=0, max_length=50, verbose_name='Mode of Payment'),
            preserve_default=False,
        ),
    ]
