# Generated by Django 3.2.7 on 2021-11-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0007_auto_20211123_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadconfirmationmodel',
            name='payment_mode',
            field=models.CharField(choices=[('ussd', 'USSD'), ('deposit', 'Deposit'), ('POS', 'POS_Transfer')], default='none', max_length=50, verbose_name='Mode of Payment'),
        ),
    ]
