# Generated by Django 3.2.7 on 2021-11-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0008_alter_uploadconfirmationmodel_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadconfirmationmodel',
            name='payment_mode',
        ),
    ]
