# Generated by Django 3.2.7 on 2021-11-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0009_remove_uploadconfirmationmodel_payment_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadConfirmationModel',
        ),
    ]
