# Generated by Django 3.2.7 on 2022-09-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=100, verbose_name='Enter your name')),
                ('Email', models.EmailField(max_length=100, verbose_name='Enter your email')),
                ('Phone', models.PositiveIntegerField(max_length=12, verbose_name='Enter your phone number')),
                ('Message', models.TextField(max_length=300, verbose_name='Leave a message')),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentConfirmUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=100, verbose_name='Username')),
                ('CLASS', models.CharField(choices=[('Prep', 'Preparatory'), ('KG', 'Kindergaten'), ('Nur_1', 'Nursery 1'), ('Nur_2', 'Nursery 2'), ('B_1', 'Basic 1'), ('B_2', 'Basic 2'), ('B_3', 'Basic 3'), ('B_4', 'Basic 4'), ('B_5', 'Basic 5'), ('Jss_1', 'JSS 1'), ('Jss_2', 'JSS 2'), ('Jss_3', 'JSS 3'), ('Sss_1', 'SSS 1')], max_length=50, verbose_name='Class')),
                ('AMOUNTPAID', models.IntegerField(max_length=50, verbose_name='Amount Paid')),
                ('BALANCE', models.IntegerField(max_length=50, verbose_name='Balance')),
                ('METHODOFPAYMENT', models.CharField(choices=[('Ussd', 'USSD'), ('Deposit', 'Deposit'), ('Pos_Trf', 'POS TRANSFER')], max_length=50, verbose_name='Payment Method')),
                ('PAYMENTUPLOAD', models.ImageField(upload_to='uploads', verbose_name='Image Confirmation')),
            ],
        ),
    ]
