# Generated by Django 3.2.7 on 2022-10-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HEADER', models.CharField(max_length=100, verbose_name='Post heading')),
                ('TITLE', models.CharField(max_length=100, verbose_name='Post title')),
                ('CONTENT', models.CharField(max_length=100, verbose_name='Post content')),
                ('IMAGE', models.ImageField(upload_to='uploads', verbose_name='Post Image')),
            ],
        ),
        migrations.AlterField(
            model_name='userpaymentconfirmupload',
            name='AMOUNTPAID',
            field=models.PositiveIntegerField(max_length=50, verbose_name='Amount Paid'),
        ),
    ]
