# Generated by Django 3.2.7 on 2022-10-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_auto_20221010_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='CONTENT',
            field=models.TextField(max_length=100, verbose_name='Post content'),
        ),
    ]
