# Generated by Django 3.2.7 on 2022-10-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='CONTENT',
            field=models.TextField(max_length=500, verbose_name='Post content'),
        ),
    ]
